// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw0mjxRbH1bpUstz3sPaGgpOF442htnXs',
    appId: '1:420500570354:web:3ca05707133fc79c79d06b',
    messagingSenderId: '420500570354',
    projectId: 'itca-proyectoai',
    authDomain: 'itca-proyectoai.firebaseapp.com',
    storageBucket: 'itca-proyectoai.firebasestorage.app',
    measurementId: 'G-ZWYMXCJFN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PXzd1-KwnIACyMnilK6D7OJ_5xXLTvU',
    appId: '1:420500570354:android:cbe1ebeea796fae379d06b',
    messagingSenderId: '420500570354',
    projectId: 'itca-proyectoai',
    storageBucket: 'itca-proyectoai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPriq3kGBrAcPMsiI5CtLvNQU-KCvImrU',
    appId: '1:420500570354:ios:c4d767d80cb42c5079d06b',
    messagingSenderId: '420500570354',
    projectId: 'itca-proyectoai',
    storageBucket: 'itca-proyectoai.firebasestorage.app',
    iosBundleId: 'com.example.aiAppTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPriq3kGBrAcPMsiI5CtLvNQU-KCvImrU',
    appId: '1:420500570354:ios:c4d767d80cb42c5079d06b',
    messagingSenderId: '420500570354',
    projectId: 'itca-proyectoai',
    storageBucket: 'itca-proyectoai.firebasestorage.app',
    iosBundleId: 'com.example.aiAppTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw0mjxRbH1bpUstz3sPaGgpOF442htnXs',
    appId: '1:420500570354:web:ed0c8c85da8c2b5579d06b',
    messagingSenderId: '420500570354',
    projectId: 'itca-proyectoai',
    authDomain: 'itca-proyectoai.firebaseapp.com',
    storageBucket: 'itca-proyectoai.firebasestorage.app',
    measurementId: 'G-M25X1CG4QF',
  );

}
